# Generated by Django 5.2.4 on 2025-07-24 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('top_up_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Top-up Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Top-up Amount')),
                ('admin_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Administration Fee')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Net Amount')),
                ('gateway_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gateway Reference')),
                ('gateway_response', models.JSONField(default=dict, verbose_name='Gateway Response')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('PR', 'Processing'), ('S', 'Successful'), ('F', 'Failed'), ('C', 'Cancelled'), ('R', 'Refunded')], default='P', max_length=2, verbose_name='Top-up Status')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('mobile_network', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Network')),
                ('bank_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Reference')),
                ('gateway_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_ups', to='configurations.paymentgatewayrequest')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_ups', to='configurations.member')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_ups', to='configurations.paymentmethod', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Top Up',
                'verbose_name_plural': 'Top Ups',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('national_id_number', models.CharField(max_length=255, unique=True, verbose_name='National ID Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Address')),
                ('physical_address', models.TextField(blank=True, null=True, verbose_name='Physical Address')),
                ('membership_number', models.CharField(editable=False, max_length=8, verbose_name='Membership Number')),
                ('dependent_code', models.CharField(editable=False, max_length=3, verbose_name='Dependent Code')),
                ('relationship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relationship')),
                ('status', models.CharField(choices=[('A', 'Active'), ('S', 'Suspended'), ('T', 'Terminated')], default='A', max_length=1, verbose_name='Status')),
                ('type', models.CharField(choices=[('P', 'Principal'), ('S', 'Spouse'), ('D', 'Dependent'), ('E', 'Employee')], max_length=1, verbose_name='Type')),
                ('annual_limit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Annual Limit')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Date Joined')),
                ('benefit_start_date', models.DateField(blank=True, null=True, verbose_name='Benefit Start Date')),
                ('suspension_start_date', models.DateField(blank=True, null=True, verbose_name='Suspension Start Date')),
                ('suspension_end_date', models.DateField(blank=True, null=True, verbose_name='Suspension End Date')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Termination Date')),
                ('other_identity_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Identity Number')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='configurations.member', verbose_name='Member')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.package', verbose_name='Benefit Package')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='membership.beneficiary', verbose_name='Principal Member')),
            ],
            options={
                'verbose_name': 'Beneficiary',
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['membership_number', 'dependent_code'],
                'unique_together': {('member', 'national_id_number'), ('membership_number', 'dependent_code')},
            },
        ),
    ]
