# Generated by Django 5.2.4 on 2025-07-27 05:34

import django.db.models.deletion
import membership.models.applicant
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_bank_registeredapplication'),
        ('membership', '0002_topup_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('application_number', models.CharField(default=membership.models.applicant.get_application_number, max_length=50, unique=True)),
                ('title', models.CharField(blank=True, choices=[('', 'Unknown'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.')], default='', max_length=10, null=True)),
                ('ethnic_group', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('', 'Unknown'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='', max_length=10, null=True)),
                ('date_of_birth', models.DateField(validators=[membership.models.applicant.validate_future_date])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('national_id', models.CharField(max_length=20, unique=True, validators=[membership.models.applicant.validate_national_id])),
                ('cell_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('physical_address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=255, null=True)),
                ('country_of_residence', models.CharField(max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('member_is_a_beneficiary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=11)),
                ('selfie_photo', models.FileField(null=True, upload_to='applicants/selfies/', verbose_name='Selfie Photo')),
                ('national_id_photo', models.FileField(null=True, upload_to='applicants/national_id/', verbose_name='National ID/Passport Photo')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='configurations.registeredapplication')),
                ('bank_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_applicants', to='configurations.bank')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant Member',
                'verbose_name_plural': 'Applicant Members',
                'ordering': ('-status', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ApplicantBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(validators=[membership.models.applicant.validate_future_date])),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Contact Number')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, validators=[membership.models.applicant.validate_beneficiary_national_id])),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('selfie_photo', models.FileField(null=True, upload_to='applicants-beneficiary/selfies/', verbose_name='Selfie Photo')),
                ('national_id_photo', models.FileField(null=True, upload_to='applicants-beneficiary/national_id/', verbose_name='National ID/Passport Photo')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='membership.applicantmember')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'Whatsapp')], max_length=255)),
                ('message', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='membership.applicantmember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='applicantmember',
            constraint=models.UniqueConstraint(fields=('national_id',), name='unique_national_id'),
        ),
        migrations.AddConstraint(
            model_name='applicantmember',
            constraint=models.UniqueConstraint(fields=('cell_number',), name='unique_cell_number'),
        ),
    ]
