# Generated by Django 5.2.4 on 2025-07-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_applicantmember_applicantbeneficiary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='membership_number',
            field=models.CharField(editable=False, max_length=10, verbose_name='Membership Number'),
        ),
    ]
