# Generated by Django 5.2.4 on 2025-07-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_beneficiary_membership_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='annual_limit',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='package',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='beneficiary/photos/', verbose_name='Profile Photo'),
        ),
    ]
