# Generated by Django 5.2.4 on 2025-07-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_remove_beneficiary_annual_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='net_amount',
        ),
        migrations.AddField(
            model_name='topup',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='topup_photos/', verbose_name='Receipt Photo'),
        ),
    ]
