# Generated by Django 5.2.4 on 2025-07-27 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudicationresult',
            name='additional_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Conditions'),
        ),
        migrations.AddField(
            model_name='adjudicationresult',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='adjudicationresult',
            name='is_modified',
            field=models.BooleanField(default=False, verbose_name='Is Modified'),
        ),
        migrations.AddField(
            model_name='adjudicationresult',
            name='partial_payment',
            field=models.BooleanField(default=False, verbose_name='Partial Payment'),
        ),
        migrations.AddField(
            model_name='adjudicationresult',
            name='qa_review_notes',
            field=models.TextField(blank=True, null=True, verbose_name='QA Review Notes'),
        ),
        migrations.AddField(
            model_name='adjudicationresult',
            name='qa_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_reviewed_results', to=settings.AUTH_USER_MODEL, verbose_name='QA Reviewed By'),
        ),
        migrations.AddField(
            model_name='adjudicationresult',
            name='requires_qa_review',
            field=models.BooleanField(default=False, verbose_name='Requires QA Review'),
        ),
        migrations.AddField(
            model_name='adjudicationresult',
            name='withheld_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Withheld Amount'),
        ),
        migrations.AddField(
            model_name='adjudicationresult',
            name='withholding_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Withholding Reason'),
        ),
        migrations.CreateModel(
            name='AdjudicationOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('original_result', models.CharField(blank=True, max_length=20, null=True, verbose_name='Original Result')),
                ('original_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Original Amount')),
                ('new_decision', models.CharField(choices=[('APPROVED', 'Manually Approved'), ('DECLINED', 'Manually Declined'), ('MODIFIED', 'Amount Modified'), ('RETURNED_TO_AUTO', 'Returned to Auto-Adjudication')], max_length=20, verbose_name='New Decision')),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='New Amount')),
                ('override_reason', models.TextField(verbose_name='Override Reason')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='Review Notes')),
                ('override_timestamp', models.DateTimeField(verbose_name='Override Timestamp')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requires Approval')),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Approval Timestamp')),
                ('financial_impact', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Financial Impact')),
                ('adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjudication_overrides', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='services.claim')),
            ],
            options={
                'verbose_name': 'Adjudication Override',
                'verbose_name_plural': 'Adjudication Overrides',
                'ordering': ['-override_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='adjudicationresult',
            name='override_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='services.adjudicationoverride'),
        ),
    ]
