# Generated by Django 5.2.4 on 2025-07-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_notify_account_credited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_applications',
            field=models.BooleanField(default=True, verbose_name='Member / Service Provider Notifications'),
        ),
    ]
