# Generated by Django 5.2.4 on 2025-07-27 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Gateway Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('base_url', models.URLField(verbose_name='Base URL')),
                ('api_endpoint', models.CharField(max_length=255, verbose_name='API Endpoint')),
                ('auth_type', models.CharField(choices=[('header', 'Header Credentials'), ('basic', 'Basic Authentication'), ('bearer', 'Bearer Token'), ('api_key', 'API Key')], default='header', max_length=10, verbose_name='Authentication Type')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Password')),
                ('api_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='API Key')),
                ('sender_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sender ID')),
                ('max_message_length', models.PositiveIntegerField(default=160, verbose_name='Max Message Length')),
                ('supports_unicode', models.BooleanField(default=False, verbose_name='Supports Unicode')),
                ('supports_delivery_reports', models.BooleanField(default=False, verbose_name='Supports Delivery Reports')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=100, verbose_name='Rate Limit per Minute')),
                ('cost_per_sms', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Cost per SMS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary Gateway')),
            ],
            options={
                'verbose_name': 'SMS Gateway',
                'verbose_name_plural': 'SMS Gateways',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='auth_type',
            field=models.CharField(choices=[('basic', 'Basic Authentication'), ('api_key', 'API Key'), ('jwt', 'JWT Token'), ('oauth', 'OAuth 2.0')], default='basic', max_length=10, verbose_name='Authentication Type'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='login_url',
            field=models.URLField(blank=True, null=True, verbose_name='JWT Login URL'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Merchant ID'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='refresh_token_field_name',
            field=models.CharField(default='refresh_token', max_length=50, verbose_name='Refresh Token Field Name'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='token_expires_in_field',
            field=models.CharField(default='expires_in', max_length=50, verbose_name='Token Expires Field Name'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='token_field_name',
            field=models.CharField(default='access_token', max_length=50, verbose_name='Token Field Name'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='token_refresh_url',
            field=models.URLField(blank=True, null=True, verbose_name='Token Refresh URL'),
        ),
        migrations.CreateModel(
            name='PaymentGatewayToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('token_type', models.CharField(default='Bearer', max_length=50, verbose_name='Token Type')),
                ('expires_in', models.PositiveIntegerField(verbose_name='Expires In (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Token Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Token Expires At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Refreshed At')),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_info', to='configurations.paymentgateway')),
            ],
            options={
                'verbose_name': 'Payment Gateway Token',
                'verbose_name_plural': 'Payment Gateway Tokens',
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('message_id', models.CharField(max_length=255, unique=True, verbose_name='Message ID')),
                ('recipient_number', models.CharField(max_length=20, verbose_name='Recipient Number')),
                ('sender_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sender ID')),
                ('message_content', models.TextField(verbose_name='Message Content')),
                ('message_type', models.CharField(choices=[('notification', 'Notification'), ('alert', 'Alert'), ('otp', 'OTP'), ('marketing', 'Marketing'), ('reminder', 'Reminder')], default='notification', max_length=15, verbose_name='Message Type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('gateway_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gateway Message ID')),
                ('gateway_response', models.JSONField(default=dict, verbose_name='Gateway Response')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Cost')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max Retries')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='configurations.agent')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='configurations.smsgateway')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='configurations.member')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='configurations.serviceprovider')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSGatewayMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field_type', models.CharField(choices=[('recipient', 'Recipient Number'), ('message', 'Message Content'), ('sender', 'Sender ID'), ('message_id', 'Message ID'), ('callback_url', 'Callback URL'), ('priority', 'Priority'), ('validity_period', 'Validity Period'), ('flash', 'Flash Message')], max_length=20, verbose_name='Field Type')),
                ('gateway_field_name', models.CharField(max_length=255, verbose_name='Gateway Field Name')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
                ('default_value', models.CharField(blank=True, max_length=500, null=True, verbose_name='Default Value')),
                ('format_rule', models.CharField(blank=True, max_length=500, null=True, verbose_name='Format Rule (e.g., +263{number})')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='configurations.smsgateway')),
            ],
            options={
                'verbose_name': 'SMS Gateway Mapping',
                'verbose_name_plural': 'SMS Gateway Mappings',
                'unique_together': {('gateway', 'field_type')},
            },
        ),
    ]
