# Generated by Django 5.2.4 on 2025-07-27 05:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_smsgateway_paymentgateway_auth_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('C', 'Commercial Bank'), ('B', 'Building Society'), ('M', 'Microfinance Bank'), ('S', 'Savings and Credit Cooperative'), ('I', 'Investment Bank'), ('D', 'Development Finance Institution'), ('O', 'Other')], default='C', max_length=1)),
                ('address', models.TextField(verbose_name='Physical Address')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone Numbers')),
                ('fax', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fax Numbers')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='RegisteredApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100)),
                ('secret', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Registered Application',
                'verbose_name_plural': 'Registered Applications',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
    ]
