# Generated by Django 5.2.4 on 2025-07-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_bank_registeredapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_number',
            field=models.CharField(db_index=True, editable=False, max_length=10, unique=True, verbose_name='Membership Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('CO', 'Corporate'), ('CM', 'Community'), ('HS', 'HealthSave'), ('IN', 'Individual'), ('FM', 'Family')], max_length=2, verbose_name='Member Type'),
        ),
    ]
