# Generated by Django 5.2.4 on 2025-07-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_alter_member_membership_number_alter_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('S', 'Suspended')], default='A', max_length=1, verbose_name='Status'),
        ),
    ]
