# Generated by Django 5.2.4 on 2025-07-29 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_alter_member_status'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('vendor_code', models.CharField(max_length=20, unique=True, verbose_name='Vendor Code')),
                ('vendor_name', models.CharField(max_length=255, verbose_name='Vendor Name')),
                ('vendor_type', models.CharField(choices=[('SP', 'Service Provider'), ('AG', 'Agent')], max_length=2, verbose_name='Vendor Type')),
                ('object_id', models.UUIDField()),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tax Rate (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('payment_terms_days', models.PositiveIntegerField(default=30, verbose_name='Payment Terms (Days)')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('serviceprovider', 'agent')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('preferred_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_vendors', to='configurations.paymentmethod', verbose_name='Preferred Payment Method')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['vendor_code'],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
