# Generated by Django 5.2.4 on 2025-07-29 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('import_type', models.CharField(choices=[('member', 'Member'), ('beneficiary', 'Beneficiary'), ('claim', 'Claim'), ('service_provider', 'Service Provider'), ('service', 'Service'), ('agent', 'Agent'), ('currency', 'Currency'), ('tier', 'Tier'), ('package', 'Package')], max_length=20, verbose_name='Import Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20, verbose_name='Status')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file_format', models.CharField(max_length=10, verbose_name='File Format')),
                ('file_size', models.PositiveIntegerField(verbose_name='File Size (bytes)')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Total Rows')),
                ('successful_rows', models.PositiveIntegerField(default=0, verbose_name='Successful Rows')),
                ('failed_rows', models.PositiveIntegerField(default=0, verbose_name='Failed Rows')),
                ('skipped_rows', models.PositiveIntegerField(default=0, verbose_name='Skipped Rows')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('import_options', models.JSONField(default=dict, verbose_name='Import Options')),
                ('summary', models.TextField(blank=True, verbose_name='Import Summary')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Imported By')),
            ],
            options={
                'verbose_name': 'Import Result',
                'verbose_name_plural': 'Import Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(verbose_name='Row Number')),
                ('error_type', models.CharField(choices=[('validation', 'Validation Error'), ('duplicate', 'Duplicate Entry'), ('missing_data', 'Missing Required Data'), ('invalid_format', 'Invalid Format'), ('foreign_key', 'Foreign Key Error'), ('business_rule', 'Business Rule Violation'), ('system', 'System Error')], max_length=20, verbose_name='Error Type')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Field Name')),
                ('error_message', models.TextField(verbose_name='Error Message')),
                ('row_data', models.JSONField(default=dict, verbose_name='Row Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('import_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_errors', to='configurations.importresult')),
            ],
            options={
                'verbose_name': 'Import Error',
                'verbose_name_plural': 'Import Errors',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportSuccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(verbose_name='Row Number')),
                ('object_id', models.CharField(max_length=100, verbose_name='Created Object ID')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Object Representation')),
                ('row_data', models.JSONField(default=dict, verbose_name='Row Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('import_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_successes', to='configurations.importresult')),
            ],
            options={
                'verbose_name': 'Import Success',
                'verbose_name_plural': 'Import Successes',
                'ordering': ['row_number'],
            },
        ),
    ]
