# Generated by Django 5.2.4 on 2025-07-24 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Balance')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Available Balance')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Pending Balance')),
                ('withheld_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Withheld Balance')),
                ('status', models.CharField(choices=[('A', 'Active'), ('S', 'Suspended'), ('F', 'Frozen'), ('C', 'Closed')], default='A', max_length=1, verbose_name='Account Status')),
                ('minimum_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Minimum Payment Amount')),
            ],
            options={
                'verbose_name': 'Provider Account',
                'verbose_name_plural': 'Provider Accounts',
                'ordering': ['service_provider__name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('transaction_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Transaction Number')),
                ('transaction_type', models.CharField(choices=[('C', 'Claim Payment'), ('W', 'Withdrawal'), ('F', 'Fee'), ('P', 'Penalty'), ('B', 'Bonus'), ('A', 'Adjustment'), ('WH', 'Withholding'), ('WR', 'Withholding Release')], max_length=2, verbose_name='Transaction Type')),
                ('amount_debited', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount Debited')),
                ('amount_credited', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount Credited')),
                ('withheld_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Withheld Amount')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Balance After')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Available Balance After')),
                ('withheld_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Withheld Balance After')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('withholding_reason', models.TextField(blank=True, null=True, verbose_name='Withholding Reason')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed'), ('R', 'Reversed')], default='P', max_length=1, verbose_name='Transaction Status')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
            ],
            options={
                'verbose_name': 'Provider Transaction',
                'verbose_name_plural': 'Provider Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopUpProcessing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('current_step', models.CharField(choices=[('initiated', 'Initiated'), ('validation', 'Validation'), ('gateway_request', 'Gateway Request'), ('gateway_response', 'Gateway Response'), ('verification', 'Verification'), ('completion', 'Completion'), ('notification', 'Notification')], default='initiated', max_length=20, verbose_name='Current Step')),
                ('step_completion', models.JSONField(default=dict, verbose_name='Step Completion Status')),
                ('validation_errors', models.JSONField(default=list, verbose_name='Validation Errors')),
                ('is_amount_valid', models.BooleanField(default=False, verbose_name='Amount Valid')),
                ('is_method_available', models.BooleanField(default=False, verbose_name='Method Available')),
                ('is_account_active', models.BooleanField(default=False, verbose_name='Account Active')),
                ('gateway_request_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gateway Request Sent At')),
                ('gateway_response_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Gateway Response Received At')),
                ('gateway_processing_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Gateway Processing Time (ms)')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max Retries')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Next Retry At')),
                ('callback_received', models.BooleanField(default=False, verbose_name='Callback Received')),
                ('callback_data', models.JSONField(default=dict, verbose_name='Callback Data')),
                ('callback_verified', models.BooleanField(default=False, verbose_name='Callback Verified')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('completion_notes', models.TextField(blank=True, null=True, verbose_name='Completion Notes')),
                ('has_errors', models.BooleanField(default=False, verbose_name='Has Errors')),
                ('error_details', models.JSONField(default=dict, verbose_name='Error Details')),
            ],
            options={
                'verbose_name': 'Top-up Processing',
                'verbose_name_plural': 'Top-up Processing',
            },
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Balance')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Available Balance')),
                ('reserved_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Reserved Balance')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Credit Limit')),
                ('overdraft_limit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Overdraft Limit')),
                ('status', models.CharField(choices=[('A', 'Active'), ('S', 'Suspended'), ('F', 'Frozen'), ('C', 'Closed')], default='A', max_length=1, verbose_name='Account Status')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Interest Rate %')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monthly Management Fee')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_accounts', to='configurations.currency')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='configurations.member')),
            ],
            options={
                'verbose_name': 'Member Account',
                'verbose_name_plural': 'Member Accounts',
                'ordering': ['member__membership_number'],
            },
        ),
        migrations.CreateModel(
            name='MemberTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('transaction_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Transaction Number')),
                ('transaction_type', models.CharField(choices=[('D', 'Deposit'), ('T', 'Top-up'), ('C', 'Claim Payment'), ('W', 'Withdrawal'), ('F', 'Fee'), ('R', 'Reserve'), ('U', 'Unreserve'), ('I', 'Interest'), ('RF', 'Refund'), ('TR', 'Transfer In'), ('TO', 'Transfer Out'), ('MF', 'Microfinance')], max_length=2, verbose_name='Transaction Type')),
                ('amount_debited', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount Debited')),
                ('amount_credited', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount Credited')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Balance After')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Available Balance After')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed'), ('R', 'Reversed')], default='P', max_length=1, verbose_name='Transaction Status')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.memberaccount')),
            ],
            options={
                'verbose_name': 'Member Transaction',
                'verbose_name_plural': 'Member Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
