# Generated by Django 5.2.4 on 2025-07-29 19:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_agentaccount_agenttransaction_paymentmethodaccount_and_more'),
        ('membership', '0006_remove_topup_net_amount_topup_photo'),
        ('services', '0002_adjudicationresult_additional_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('transfer_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Transfer Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Transfer Amount')),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Transfer Fee')),
                ('transfer_type', models.CharField(choices=[('cash_deposit', 'Cash Deposit to Bank'), ('cash_withdrawal', 'Cash Withdrawal from Bank'), ('bank_transfer', 'Bank to Bank Transfer'), ('wallet_transfer', 'Wallet to Wallet Transfer'), ('general_transfer', 'General Transfer')], max_length=20, verbose_name='Transfer Type')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed'), ('R', 'Reversed')], default='P', max_length=1, verbose_name='Transfer Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
            ],
            options={
                'verbose_name': 'Payment Method Transfer',
                'verbose_name_plural': 'Payment Method Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentmethodtransaction',
            name='agent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_method_transactions', to='accounting.agenttransaction', verbose_name='Related Agent Transaction'),
        ),
        migrations.AddField(
            model_name='paymentmethodtransaction',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_method_transactions', to='services.claim', verbose_name='Related Claim'),
        ),
        migrations.AddField(
            model_name='paymentmethodtransaction',
            name='top_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_method_transactions', to='membership.topup', verbose_name='Related Top-up'),
        ),
        migrations.AddField(
            model_name='paymentmethodtransaction',
            name='transfer_from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to_transactions', to='accounting.paymentmethodaccount', verbose_name='Transfer From Account'),
        ),
        migrations.AddField(
            model_name='paymentmethodtransaction',
            name='transfer_to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from_transactions', to='accounting.paymentmethodaccount', verbose_name='Transfer To Account'),
        ),
    ]
