# Generated by Django 5.2.4 on 2025-07-29 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_paymentmethodtransfer_and_more'),
        ('configurations', '0006_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodtransaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_method_transactions', to='configurations.vendor', verbose_name='Related Vendor'),
        ),
        migrations.AlterField(
            model_name='paymentmethodtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('top_up', 'Top-up Amount'), ('top_up_fee', 'Top-up Processing Fee'), ('claim_payment', 'Claim Payment'), ('claim_fee', 'Claim Processing Fee'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('cash_deposit', 'Cash Deposit'), ('cash_withdrawal', 'Cash Withdrawal'), ('bank_deposit', 'Bank Deposit'), ('bank_withdrawal', 'Bank Withdrawal'), ('refund', 'Refund'), ('adjustment', 'Manual Adjustment'), ('reconciliation', 'Reconciliation'), ('gateway_fee', 'Gateway Fee'), ('settlement', 'Settlement'), ('chargeback', 'Chargeback'), ('provider_payment', 'Provider Payment'), ('agent_commission', 'Agent Commission Payment'), ('vendor_payment', 'Vendor Payment')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AddField(
            model_name='paymentmethodtransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='accounting.paymentmethodaccount', verbose_name='From Account'),
        ),
        migrations.AddField(
            model_name='paymentmethodtransfer',
            name='from_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfer', to='accounting.paymentmethodtransaction', verbose_name='From Transaction'),
        ),
        migrations.AddField(
            model_name='paymentmethodtransfer',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payment_method_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AddField(
            model_name='paymentmethodtransfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='accounting.paymentmethodaccount', verbose_name='To Account'),
        ),
        migrations.AddField(
            model_name='paymentmethodtransfer',
            name='to_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfer', to='accounting.paymentmethodtransaction', verbose_name='To Transaction'),
        ),
    ]
